version: 0.2

phases:
  install:
    runtime-versions:
      java: java21
    commands:
      - echo "Installing dependencies"
      - mvn clean package
  build:
    commands:
      - echo "Listing target directory..."
      - ls -la target/
      - mkdir -p lambda
      - cp target/csv-report-lambda-1.0-SNAPSHOT.jar lambda/csv-report-lambda.jar
      - echo "Checking lambda directory..."
      - ls -la lambda/
      - echo "Packaging Lambda function..."
      - sam package --output-template-file packaged.yaml --s3-bucket olena-sinkevych-bucket3 --region us-east-1

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
