version: 0.2

phases:
  install:
    runtime-versions:
      java: java21
    commands:
      - echo "Installing dependencies"
      - mvn install
  build:
    commands:
      - echo "Building the Java project"
      - mvn package
      - echo "Packaging Lambda function with SAM"
      - sam package --output-template-file packaged.yaml --s3-bucket olena-sinkevych-bucket3

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
